<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="human-PC" name="Test" tests="40" failures="5" timestamp="1 Apr 2016 02:27:16 GMT" time="322.976" errors="0">
  <testcase name="saveOrUpdateUnitTest" time="5.474" classname="Testcase.APIsaveOrUpdateUnitTest"/>
  <testcase name="queryUnitByIdTest" time="0.61" classname="Testcase.APIqueryUnitByIdTest"/>
  <testcase name="delUnitByIdTest" time="2.655" classname="Testcase.APIdelUnitByIdTest"/>
  <testcase name="queryUnitPagerTest" time="1.843" classname="Testcase.APIqueryUnitPagerTest"/>
  <testcase name="saveCatTest" time="3.644" classname="Testcase.APIsaveCatTest"/>
  <testcase name="updateCatNameTest" time="3.826" classname="Testcase.APIupdateCatNameTest"/>
  <testcase name="delCatTest" time="3.37" classname="Testcase.APIdelCatTest"/>
  <testcase name="queryCatListTest" time="0.73" classname="Testcase.APIqueryCatListTest"/>
  <testcase name="queryCatByIdTest" time="0.565" classname="Testcase.APIqueryCatByIdTest"/>
  <testcase name="barCreatorTest" time="0.201" classname="Testcase.APIbarCreatorTest"/>
  <testcase name="queryGoodsLibraryTest" time="0.324" classname="Testcase.APIqueryGoodsLibraryTest"/>
  <testcase name="saveGoodsTest" time="11.085" classname="Testcase.APIsaveGoodsTest">
    <failure type="java.lang.AssertionError" message="+++ expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: +++ expected [true] but found [false]
	at Testcase.APIsaveGoodsTest.saveGoodsTest(APIsaveGoodsTest.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- saveGoodsTest -->
  <testcase name="updateGoodsTest" time="13.808" classname="Testcase.APIupdateGoodsTest">
    <failure type="java.lang.AssertionError" message="+++ expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: +++ expected [true] but found [false]
	at Testcase.APIupdateGoodsTest.updateGoodsTest(APIupdateGoodsTest.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- updateGoodsTest -->
  <testcase name="queryGoodsByIdTest" time="0.514" classname="Testcase.APIqueryGoodsByIdTest"/>
  <testcase name="delGoodsTest" time="0.976" classname="Testcase.APIdelGoodsTest"/>
  <testcase name="queryGoodsPagerTest" time="0.813" classname="Testcase.APIqueryGoodsPagerTest"/>
  <testcase name="updateIntegralRuleTest" time="4.223" classname="Testcase.APIupdateIntegralRuleTest"/>
  <testcase name="queryIntegralRuleTest" time="0.525" classname="Testcase.APIqueryIntegralRuleTest"/>
  <testcase name="addOrModifyVipTypeTest" time="8.392" classname="Testcase.APIaddOrModifyVipTypeTest"/>
  <testcase name="delVipTypeTest" time="1.477" classname="Testcase.APIdelVipTypeTest"/>
  <testcase name="queryVipTypeListTest" time="0.599" classname="Testcase.APIqueryVipTypeListTest"/>
  <testcase name="saveVipStoreRuleDetailTest" time="5.297" classname="Testcase.APIsaveVipStoreRuleDetailTest"/>
  <testcase name="delVipStoreRuleDetailTest" time="3.113" classname="Testcase.APIdelVipStoreRuleDetailTest"/>
  <testcase name="queryVipStoreRuleTest" time="0.867" classname="Testcase.APIqueryVipStoreRuleTest"/>
  <testcase name="updateVipStoreRuleDetailTest" time="2.991" classname="Testcase.APIupdateVipStoreRuleDetailTest"/>
  <testcase name="startOrCloseVipStoreRuleTest" time="1.214" classname="Testcase.APIstartOrCloseVipStoreRuleTest"/>
  <testcase name="qryVipListTest" time="3.283" classname="Testcase.APIqryVipListTest"/>
  <testcase name="queryEmpPagerTest" time="2.139" classname="Testcase.APIqueryEmpPagerTest"/>
  <testcase name="queryRolePagerTest" time="0.401" classname="Testcase.APIqueryRolePagerTest"/>
  <testcase name="saveEmpTest" time="31.435" classname="Testcase.APIsaveEmpTest">
    <failure type="java.lang.AssertionError" message="+++ expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: +++ expected [true] but found [false]
	at Testcase.APIsaveEmpTest.saveEmpTest(APIsaveEmpTest.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- saveEmpTest -->
  <testcase name="updateEmpTest" time="179.244" classname="Testcase.APIupdateEmpTest">
    <failure type="java.lang.AssertionError" message="+++ expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: +++ expected [true] but found [false]
	at Testcase.APIupdateEmpTest.updateEmpTest(APIupdateEmpTest.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- updateEmpTest -->
  <testcase name="delEmpTest" time="2.263" classname="Testcase.APIdelEmpTest"/>
  <testcase name="nextEmpCodeTest" time="1.006" classname="Testcase.APInextEmpCodeTest"/>
  <testcase name="resetPasswordForLocalTest" time="2.05" classname="Testcase.APIresetPasswordForLocalTest"/>
  <testcase name="paymentListTest" time="1.78" classname="Testcase.APIpaymentListTest"/>
  <testcase name="findPaymentByIdTest" time="1.111" classname="Testcase.APIfindPaymentByIdTest"/>
  <testcase name="deletePaymentsTest" time="4.455" classname="Testcase.APIdeletePaymentsTest"/>
  <testcase name="isEnablePaymentTest" time="1.676" classname="Testcase.APIisEnablePaymentTest"/>
  <testcase name="scoreOrNotTest" time="2.05" classname="Testcase.APIscoreOrNotTest"/>
  <testcase name="savePaymentTest" time="10.885" classname="Testcase.APIsavePaymentTest">
    <failure type="java.lang.AssertionError" message="+++ expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: +++ expected [true] but found [false]
	at Testcase.APIsavePaymentTest.savePaymentTest(APIsavePaymentTest.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- savePaymentTest -->
</testsuite> <!-- Test -->
